### ISSUE TITLE
storage of data

### ISSUE THREAD

**Issue by BizDevGeek** [peterh/obd2csv#1]
Hi, I see that you're using CSV files to save the OBD2 data. I'm working on a project to save it to a database instead. Shoot me an email (jozefnagyjr@gmail.com) so we can share some of what we're working on. I'd like to create a storage service for OBD2 that's easier to use with large volumes of data.

**Comment by peterh** [comment]
Thanks for asking. I don't have any interest in databases personally, but you're welcome to fork if obd2csv is a useful starting point for you.
