### ISSUE TITLE
Usage with perl 5.24.1

### ISSUE THREAD

**Issue by OE2WNL** [peterh/obd2csv#2]
Hi!
Regarding the
`no 5.20.0;` in obd2csv.pl line 23

I would like to use this script on a Raspberry Pi Zero with raspbian which now ships with Perl 5.24.1
Is it save to just comment out this line?

Thank you and greetings
Wolfgang

**Comment by peterh** [comment]
It works for me when commenting out that line. I can't guarantee it will keep working after the next perl update, because they retroactively marked some features experimental.

**Comment by OE2WNL** [comment]
Thank you for your quick response! I'll keep fingers crossed and try :-)
